version: '3.8'
services:
  chatgpt-mirror-server:
    image: xyhelper/chatgpt-mirror-server:latest
    restart: always
    ports:
      - 8100:8001
    environment:
      TZ: Asia/Shanghai # 指定时区
      # 接入网关地址
      CHATPROXY: "https://demo.xyhelper.cn"
      # 接入网关的authkey
      AUTHKEY: "xyhelper"
      # 是否只使用token验证
      ONLYTOKEN: true 
      # API对接验证
      # APIAUTH: "myauthkey"
    volumes:
      - ./data/chatgpt-mirror-server/:/app/data/
